"""
生成 assets/cefr_wordlist.csv
資料來源：依據 Oxford 5000 / Cambridge EVP 整理的 B1-C2 詞彙
"""
import csv
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

OUTPUT_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                           "assets", "cefr_wordlist.csv")

# 格式：(word, cefr_level, part_of_speech)
WORDLIST = [
    # ── B1 ──────────────────────────────────────────────────────────────────
    ("ability", "B1", "n."), ("absence", "B1", "n."), ("absolutely", "B1", "adv."),
    ("accept", "B1", "vt."), ("access", "B1", "n."), ("accident", "B1", "n."),
    ("according", "B1", "adv."), ("achieve", "B1", "vt."), ("activity", "B1", "n."),
    ("actually", "B1", "adv."), ("addition", "B1", "n."), ("address", "B1", "vt."),
    ("admire", "B1", "vt."), ("admit", "B1", "vt."), ("advantage", "B1", "n."),
    ("adventure", "B1", "n."), ("advertise", "B1", "vt."), ("advice", "B1", "n."),
    ("affect", "B1", "vt."), ("afford", "B1", "vt."), ("afraid", "B1", "adj."),
    ("agree", "B1", "vi."), ("allow", "B1", "vt."), ("although", "B1", "conj."),
    ("amount", "B1", "n."), ("announce", "B1", "vt."), ("appear", "B1", "vi."),
    ("apply", "B1", "vt."), ("argue", "B1", "vi."), ("arrange", "B1", "vt."),
    ("arrive", "B1", "vi."), ("article", "B1", "n."), ("artist", "B1", "n."),
    ("aspect", "B1", "n."), ("assist", "B1", "vt."), ("assume", "B1", "vt."),
    ("attempt", "B1", "vt."), ("attend", "B1", "vt."), ("attitude", "B1", "n."),
    ("attract", "B1", "vt."), ("audience", "B1", "n."), ("automatic", "B1", "adj."),
    ("avoid", "B1", "vt."), ("aware", "B1", "adj."), ("awful", "B1", "adj."),
    ("background", "B1", "n."), ("basic", "B1", "adj."), ("beat", "B1", "vt."),
    ("behave", "B1", "vi."), ("belief", "B1", "n."), ("belong", "B1", "vi."),
    ("benefit", "B1", "n."), ("bite", "B1", "vt."), ("bother", "B1", "vt."),
    ("brave", "B1", "adj."), ("breathe", "B1", "vi."), ("bright", "B1", "adj."),
    ("brilliant", "B1", "adj."), ("calm", "B1", "adj."), ("campaign", "B1", "n."),
    ("capable", "B1", "adj."), ("career", "B1", "n."), ("careful", "B1", "adj."),
    ("cause", "B1", "vt."), ("celebrate", "B1", "vt."), ("central", "B1", "adj."),
    ("challenge", "B1", "n."), ("chance", "B1", "n."), ("character", "B1", "n."),
    ("charge", "B1", "vt."), ("chase", "B1", "vt."), ("choose", "B1", "vt."),
    ("citizen", "B1", "n."), ("claim", "B1", "vt."), ("clear", "B1", "adj."),
    ("clever", "B1", "adj."), ("collect", "B1", "vt."), ("comment", "B1", "vi."),
    ("communicate", "B1", "vi."), ("community", "B1", "n."), ("compare", "B1", "vt."),
    ("compete", "B1", "vi."), ("complete", "B1", "vt."), ("concentrate", "B1", "vi."),
    ("condition", "B1", "n."), ("confident", "B1", "adj."), ("connect", "B1", "vt."),
    ("consider", "B1", "vt."), ("contact", "B1", "vt."), ("continue", "B1", "vi."),
    ("control", "B1", "vt."), ("convenient", "B1", "adj."), ("correct", "B1", "adj."),
    ("cost", "B1", "n."), ("creative", "B1", "adj."), ("current", "B1", "adj."),
    ("customer", "B1", "n."), ("damage", "B1", "vt."), ("deal", "B1", "vi."),
    ("decide", "B1", "vt."), ("delay", "B1", "vt."), ("depend", "B1", "vi."),
    ("describe", "B1", "vt."), ("design", "B1", "vt."), ("develop", "B1", "vt."),
    ("difference", "B1", "n."), ("difficult", "B1", "adj."), ("discuss", "B1", "vt."),
    ("distance", "B1", "n."), ("dream", "B1", "vi."), ("effect", "B1", "n."),
    ("effort", "B1", "n."), ("either", "B1", "adv."), ("else", "B1", "adv."),
    ("emphasize", "B1", "vt."), ("encourage", "B1", "vt."), ("environment", "B1", "n."),
    ("equal", "B1", "adj."), ("event", "B1", "n."), ("evidence", "B1", "n."),
    ("exact", "B1", "adj."), ("example", "B1", "n."), ("excellent", "B1", "adj."),
    ("except", "B1", "prep."), ("expect", "B1", "vt."), ("experience", "B1", "n."),
    ("explain", "B1", "vt."), ("express", "B1", "vt."), ("fail", "B1", "vi."),
    ("familiar", "B1", "adj."), ("famous", "B1", "adj."), ("fantastic", "B1", "adj."),
    ("feature", "B1", "n."), ("feeling", "B1", "n."), ("flexible", "B1", "adj."),
    ("focus", "B1", "vi."), ("follow", "B1", "vt."), ("fond", "B1", "adj."),
    ("force", "B1", "vt."), ("forget", "B1", "vt."), ("freedom", "B1", "n."),
    ("friendly", "B1", "adj."), ("frustrated", "B1", "adj."), ("general", "B1", "adj."),
    ("genuine", "B1", "adj."), ("global", "B1", "adj."), ("goal", "B1", "n."),
    ("grateful", "B1", "adj."), ("handle", "B1", "vt."), ("happen", "B1", "vi."),
    ("healthy", "B1", "adj."), ("honest", "B1", "adj."), ("imagine", "B1", "vt."),
    ("improve", "B1", "vt."), ("include", "B1", "vt."), ("independent", "B1", "adj."),
    ("individual", "B1", "n."), ("influence", "B1", "vt."), ("interest", "B1", "n."),
    ("introduce", "B1", "vt."), ("invite", "B1", "vt."), ("involve", "B1", "vt."),
    ("join", "B1", "vt."), ("journey", "B1", "n."), ("judge", "B1", "vt."),
    ("knowledge", "B1", "n."), ("lack", "B1", "vt."), ("language", "B1", "n."),
    ("leader", "B1", "n."), ("lend", "B1", "vt."), ("limit", "B1", "vt."),
    ("local", "B1", "adj."), ("logical", "B1", "adj."), ("manage", "B1", "vt."),
    ("media", "B1", "n."), ("memory", "B1", "n."), ("mention", "B1", "vt."),
    ("method", "B1", "n."), ("miss", "B1", "vt."), ("modern", "B1", "adj."),
    ("natural", "B1", "adj."), ("necessary", "B1", "adj."), ("nervous", "B1", "adj."),
    ("notice", "B1", "vt."), ("object", "B1", "n."), ("opportunity", "B1", "n."),
    ("option", "B1", "n."), ("organize", "B1", "vt."), ("original", "B1", "adj."),
    ("otherwise", "B1", "adv."), ("particular", "B1", "adj."), ("perhaps", "B1", "adv."),
    ("permission", "B1", "n."), ("personal", "B1", "adj."), ("popular", "B1", "adj."),
    ("possible", "B1", "adj."), ("prepare", "B1", "vt."), ("present", "B1", "vt."),
    ("prevent", "B1", "vt."), ("process", "B1", "n."), ("produce", "B1", "vt."),
    ("progress", "B1", "n."), ("project", "B1", "n."), ("protect", "B1", "vt."),
    ("provide", "B1", "vt."), ("publish", "B1", "vt."), ("purpose", "B1", "n."),
    ("quality", "B1", "n."), ("quite", "B1", "adv."), ("realize", "B1", "vt."),
    ("reason", "B1", "n."), ("receive", "B1", "vt."), ("recent", "B1", "adj."),
    ("recognize", "B1", "vt."), ("reduce", "B1", "vt."), ("refer", "B1", "vi."),
    ("relationship", "B1", "n."), ("rely", "B1", "vi."), ("replace", "B1", "vt."),
    ("require", "B1", "vt."), ("research", "B1", "n."), ("respect", "B1", "vt."),
    ("result", "B1", "n."), ("risk", "B1", "n."), ("rule", "B1", "n."),
    ("save", "B1", "vt."), ("section", "B1", "n."), ("select", "B1", "vt."),
    ("serious", "B1", "adj."), ("share", "B1", "vt."), ("similar", "B1", "adj."),
    ("simple", "B1", "adj."), ("situation", "B1", "n."), ("skill", "B1", "n."),
    ("society", "B1", "n."), ("solve", "B1", "vt."), ("special", "B1", "adj."),
    ("spend", "B1", "vt."), ("standard", "B1", "n."), ("step", "B1", "n."),
    ("strange", "B1", "adj."), ("study", "B1", "vt."), ("subject", "B1", "n."),
    ("succeed", "B1", "vi."), ("suggest", "B1", "vt."), ("support", "B1", "vt."),
    ("surprise", "B1", "vt."), ("technology", "B1", "n."), ("therefore", "B1", "adv."),
    ("through", "B1", "prep."), ("traditional", "B1", "adj."), ("trust", "B1", "vt."),
    ("truth", "B1", "n."), ("typical", "B1", "adj."), ("unless", "B1", "conj."),
    ("unusual", "B1", "adj."), ("useful", "B1", "adj."), ("various", "B1", "adj."),
    ("volunteer", "B1", "vi."), ("whereas", "B1", "conj."), ("worry", "B1", "vi."),
    ("worth", "B1", "adj."),

    # ── B2 ──────────────────────────────────────────────────────────────────
    ("abandon", "B2", "vt."), ("abstract", "B2", "adj."), ("abundant", "B2", "adj."),
    ("accelerate", "B2", "vt."), ("access", "B2", "vt."), ("accommodate", "B2", "vt."),
    ("accomplish", "B2", "vt."), ("accountable", "B2", "adj."), ("accurate", "B2", "adj."),
    ("acknowledge", "B2", "vt."), ("acquire", "B2", "vt."), ("adapt", "B2", "vt."),
    ("adequate", "B2", "adj."), ("administration", "B2", "n."), ("adopt", "B2", "vt."),
    ("advocate", "B2", "vt."), ("aggravate", "B2", "vt."), ("aggressive", "B2", "adj."),
    ("allocate", "B2", "vt."), ("alter", "B2", "vt."), ("alternative", "B2", "n."),
    ("ambition", "B2", "n."), ("analyze", "B2", "vt."), ("anticipate", "B2", "vt."),
    ("apparent", "B2", "adj."), ("appreciate", "B2", "vt."), ("appropriate", "B2", "adj."),
    ("approve", "B2", "vt."), ("approximately", "B2", "adv."), ("arise", "B2", "vi."),
    ("assess", "B2", "vt."), ("assign", "B2", "vt."), ("associate", "B2", "vt."),
    ("assume", "B2", "vt."), ("attain", "B2", "vt."), ("authorize", "B2", "vt."),
    ("capable", "B2", "adj."), ("capture", "B2", "vt."), ("category", "B2", "n."),
    ("circulate", "B2", "vt."), ("circumstance", "B2", "n."), ("clarify", "B2", "vt."),
    ("collaborate", "B2", "vi."), ("commitment", "B2", "n."), ("compensate", "B2", "vt."),
    ("complex", "B2", "adj."), ("component", "B2", "n."), ("comprehensive", "B2", "adj."),
    ("conceive", "B2", "vt."), ("conduct", "B2", "vt."), ("consequence", "B2", "n."),
    ("consistent", "B2", "adj."), ("consume", "B2", "vt."), ("contribute", "B2", "vi."),
    ("controversial", "B2", "adj."), ("convenient", "B2", "adj."), ("convince", "B2", "vt."),
    ("cope", "B2", "vi."), ("corporation", "B2", "n."), ("correspond", "B2", "vi."),
    ("critical", "B2", "adj."), ("crucial", "B2", "adj."), ("cultivate", "B2", "vt."),
    ("dedicate", "B2", "vt."), ("deliberate", "B2", "adj."), ("demonstrate", "B2", "vt."),
    ("deny", "B2", "vt."), ("derive", "B2", "vt."), ("detect", "B2", "vt."),
    ("determine", "B2", "vt."), ("devote", "B2", "vt."), ("distinct", "B2", "adj."),
    ("distribute", "B2", "vt."), ("domestic", "B2", "adj."), ("dominate", "B2", "vt."),
    ("drastically", "B2", "adv."), ("dynamic", "B2", "adj."), ("elaborate", "B2", "vt."),
    ("eliminate", "B2", "vt."), ("emerge", "B2", "vi."), ("enable", "B2", "vt."),
    ("enforce", "B2", "vt."), ("enormous", "B2", "adj."), ("ensure", "B2", "vt."),
    ("enterprise", "B2", "n."), ("entire", "B2", "adj."), ("evaluate", "B2", "vt."),
    ("eventually", "B2", "adv."), ("evolve", "B2", "vi."), ("exceed", "B2", "vt."),
    ("exclude", "B2", "vt."), ("expand", "B2", "vt."), ("exploit", "B2", "vt."),
    ("expose", "B2", "vt."), ("extensive", "B2", "adj."), ("extreme", "B2", "adj."),
    ("facilitate", "B2", "vt."), ("fundamental", "B2", "adj."), ("generate", "B2", "vt."),
    ("gradual", "B2", "adj."), ("guarantee", "B2", "vt."), ("identify", "B2", "vt."),
    ("illustrate", "B2", "vt."), ("implement", "B2", "vt."), ("imply", "B2", "vt."),
    ("impose", "B2", "vt."), ("indicate", "B2", "vt."), ("inevitable", "B2", "adj."),
    ("integrate", "B2", "vt."), ("interaction", "B2", "n."), ("interpret", "B2", "vt."),
    ("investigate", "B2", "vt."), ("justify", "B2", "vt."), ("launch", "B2", "vt."),
    ("legislation", "B2", "n."), ("legitimate", "B2", "adj."), ("maintain", "B2", "vt."),
    ("massive", "B2", "adj."), ("mechanism", "B2", "n."), ("minimize", "B2", "vt."),
    ("modify", "B2", "vt."), ("monitor", "B2", "vt."), ("motivate", "B2", "vt."),
    ("negotiate", "B2", "vi."), ("numerous", "B2", "adj."), ("obvious", "B2", "adj."),
    ("occupy", "B2", "vt."), ("occur", "B2", "vi."), ("outcome", "B2", "n."),
    ("overcome", "B2", "vt."), ("parallel", "B2", "adj."), ("perceive", "B2", "vt."),
    ("perform", "B2", "vt."), ("persistent", "B2", "adj."), ("perspective", "B2", "n."),
    ("phenomenon", "B2", "n."), ("policy", "B2", "n."), ("potential", "B2", "adj."),
    ("precise", "B2", "adj."), ("predict", "B2", "vt."), ("priority", "B2", "n."),
    ("promote", "B2", "vt."), ("proportion", "B2", "n."), ("pursue", "B2", "vt."),
    ("recognize", "B2", "vt."), ("recover", "B2", "vi."), ("regulate", "B2", "vt."),
    ("reinforce", "B2", "vt."), ("relevant", "B2", "adj."), ("represent", "B2", "vt."),
    ("require", "B2", "vt."), ("resolve", "B2", "vt."), ("resource", "B2", "n."),
    ("restrict", "B2", "vt."), ("reveal", "B2", "vt."), ("role", "B2", "n."),
    ("sector", "B2", "n."), ("significant", "B2", "adj."), ("sophisticated", "B2", "adj."),
    ("source", "B2", "n."), ("specific", "B2", "adj."), ("stable", "B2", "adj."),
    ("strategy", "B2", "n."), ("structure", "B2", "n."), ("subsequent", "B2", "adj."),
    ("sufficient", "B2", "adj."), ("sustainable", "B2", "adj."), ("tackle", "B2", "vt."),
    ("target", "B2", "n."), ("tend", "B2", "vi."), ("transfer", "B2", "vt."),
    ("transform", "B2", "vt."), ("trend", "B2", "n."), ("undergo", "B2", "vt."),
    ("undertake", "B2", "vt."), ("unique", "B2", "adj."), ("utilize", "B2", "vt."),
    ("vary", "B2", "vi."), ("vulnerable", "B2", "adj."), ("widespread", "B2", "adj."),
    ("yield", "B2", "vt."),

    # ── C1 ──────────────────────────────────────────────────────────────────
    ("abolish", "C1", "vt."), ("absurd", "C1", "adj."), ("accelerate", "C1", "vt."),
    ("acclaim", "C1", "vt."), ("accomodate", "C1", "vt."), ("accumulate", "C1", "vt."),
    ("adhere", "C1", "vi."), ("affluent", "C1", "adj."), ("allegation", "C1", "n."),
    ("alleviate", "C1", "vt."), ("ambiguous", "C1", "adj."), ("analogous", "C1", "adj."),
    ("articulate", "C1", "vt."), ("aspire", "C1", "vi."), ("assert", "C1", "vt."),
    ("assumption", "C1", "n."), ("atrocity", "C1", "n."), ("attribute", "C1", "vt."),
    ("augment", "C1", "vt."), ("autonomous", "C1", "adj."), ("benchmark", "C1", "n."),
    ("bias", "C1", "n."), ("breakthrough", "C1", "n."), ("candid", "C1", "adj."),
    ("chronic", "C1", "adj."), ("coherent", "C1", "adj."), ("coincide", "C1", "vi."),
    ("collective", "C1", "adj."), ("compelling", "C1", "adj."), ("competence", "C1", "n."),
    ("complement", "C1", "vt."), ("comply", "C1", "vi."), ("concede", "C1", "vt."),
    ("concurrent", "C1", "adj."), ("confine", "C1", "vt."), ("consensus", "C1", "n."),
    ("consolidate", "C1", "vt."), ("contemplate", "C1", "vt."), ("contradict", "C1", "vt."),
    ("critique", "C1", "n."), ("cynical", "C1", "adj."), ("debris", "C1", "n."),
    ("decline", "C1", "vi."), ("defy", "C1", "vt."), ("deliberate", "C1", "vt."),
    ("depict", "C1", "vt."), ("deplete", "C1", "vt."), ("designate", "C1", "vt."),
    ("deteriorate", "C1", "vi."), ("deviate", "C1", "vi."), ("diminish", "C1", "vt."),
    ("discrepancy", "C1", "n."), ("disrupt", "C1", "vt."), ("distinction", "C1", "n."),
    ("diverge", "C1", "vi."), ("diversity", "C1", "n."), ("dominant", "C1", "adj."),
    ("elaborate", "C1", "adj."), ("empirical", "C1", "adj."), ("encounter", "C1", "vt."),
    ("endorse", "C1", "vt."), ("enhance", "C1", "vt."), ("enlighten", "C1", "vt."),
    ("epidemic", "C1", "n."), ("eradicate", "C1", "vt."), ("erosion", "C1", "n."),
    ("evoke", "C1", "vt."), ("exaggerate", "C1", "vt."), ("exempt", "C1", "vt."),
    ("exhaustive", "C1", "adj."), ("explicit", "C1", "adj."), ("exploit", "C1", "n."),
    ("fabricate", "C1", "vt."), ("falter", "C1", "vi."), ("fluctuate", "C1", "vi."),
    ("formulate", "C1", "vt."), ("fragile", "C1", "adj."), ("framework", "C1", "n."),
    ("frustrate", "C1", "vt."), ("fundamental", "C1", "adj."), ("grant", "C1", "vt."),
    ("grievance", "C1", "n."), ("hierarchy", "C1", "n."), ("hypothesis", "C1", "n."),
    ("ideology", "C1", "n."), ("illusion", "C1", "n."), ("imminent", "C1", "adj."),
    ("implicit", "C1", "adj."), ("incentive", "C1", "n."), ("incompatible", "C1", "adj."),
    ("incur", "C1", "vt."), ("indispensable", "C1", "adj."), ("infer", "C1", "vt."),
    ("infrastructure", "C1", "n."), ("inherent", "C1", "adj."), ("inhibit", "C1", "vt."),
    ("integrity", "C1", "n."), ("intervene", "C1", "vi."), ("intuition", "C1", "n."),
    ("invoke", "C1", "vt."), ("legitimate", "C1", "adj."), ("magnitude", "C1", "n."),
    ("manipulate", "C1", "vt."), ("manifest", "C1", "vt."), ("marginalize", "C1", "vt."),
    ("mediate", "C1", "vt."), ("mitigate", "C1", "vt."), ("momentum", "C1", "n."),
    ("mutual", "C1", "adj."), ("narrative", "C1", "n."), ("negate", "C1", "vt."),
    ("nonetheless", "C1", "adv."), ("notion", "C1", "n."), ("nurture", "C1", "vt."),
    ("objective", "C1", "adj."), ("obsolete", "C1", "adj."), ("obtain", "C1", "vt."),
    ("optimistic", "C1", "adj."), ("overwhelm", "C1", "vt."), ("paradox", "C1", "n."),
    ("perceive", "C1", "vt."), ("persist", "C1", "vi."), ("plausible", "C1", "adj."),
    ("pragmatic", "C1", "adj."), ("precedent", "C1", "n."), ("prevail", "C1", "vi."),
    ("proficient", "C1", "adj."), ("profound", "C1", "adj."), ("prohibit", "C1", "vt."),
    ("prominent", "C1", "adj."), ("protocol", "C1", "n."), ("provoke", "C1", "vt."),
    ("pursuant", "C1", "adj."), ("rationale", "C1", "n."), ("reciprocal", "C1", "adj."),
    ("reconcile", "C1", "vt."), ("redundant", "C1", "adj."), ("reinstate", "C1", "vt."),
    ("relinquish", "C1", "vt."), ("resilience", "C1", "n."), ("robust", "C1", "adj."),
    ("scrutinize", "C1", "vt."), ("simultaneously", "C1", "adv."), ("skeptical", "C1", "adj."),
    ("so-called", "C1", "adj."), ("spontaneous", "C1", "adj."), ("stimulate", "C1", "vt."),
    ("stringent", "C1", "adj."), ("subjective", "C1", "adj."), ("subordinate", "C1", "adj."),
    ("subsequently", "C1", "adv."), ("suppress", "C1", "vt."), ("susceptible", "C1", "adj."),
    ("sustain", "C1", "vt."), ("synthesis", "C1", "n."), ("tactic", "C1", "n."),
    ("tangible", "C1", "adj."), ("threshold", "C1", "n."), ("transparent", "C1", "adj."),
    ("trigger", "C1", "vt."), ("ubiquitous", "C1", "adj."), ("ultimately", "C1", "adv."),
    ("unprecedented", "C1", "adj."), ("validate", "C1", "vt."), ("viable", "C1", "adj."),
    ("volatile", "C1", "adj."),

    # ── C2 ──────────────────────────────────────────────────────────────────
    ("abhor", "C2", "vt."), ("aberration", "C2", "n."), ("abrogate", "C2", "vt."),
    ("acrimony", "C2", "n."), ("adamant", "C2", "adj."), ("admonish", "C2", "vt."),
    ("adroit", "C2", "adj."), ("adversarial", "C2", "adj."), ("aesthetic", "C2", "adj."),
    ("albeit", "C2", "conj."), ("aloof", "C2", "adj."), ("altruism", "C2", "n."),
    ("ambivalent", "C2", "adj."), ("ameliorate", "C2", "vt."), ("anachronism", "C2", "n."),
    ("anarchy", "C2", "n."), ("annihilate", "C2", "vt."), ("apathy", "C2", "n."),
    ("archaic", "C2", "adj."), ("arduous", "C2", "adj."), ("articulate", "C2", "adj."),
    ("astute", "C2", "adj."), ("audacious", "C2", "adj."), ("auspicious", "C2", "adj."),
    ("axiom", "C2", "n."), ("bellicose", "C2", "adj."), ("benevolent", "C2", "adj."),
    ("blatant", "C2", "adj."), ("brevity", "C2", "n."), ("byzantine", "C2", "adj."),
    ("cacophony", "C2", "n."), ("capitulate", "C2", "vi."), ("capricious", "C2", "adj."),
    ("catharsis", "C2", "n."), ("circumspect", "C2", "adj."), ("clandestine", "C2", "adj."),
    ("coerce", "C2", "vt."), ("cogent", "C2", "adj."), ("complacent", "C2", "adj."),
    ("condone", "C2", "vt."), ("convoluted", "C2", "adj."), ("corroborate", "C2", "vt."),
    ("counterfeit", "C2", "vt."), ("curtail", "C2", "vt."), ("dearth", "C2", "n."),
    ("debacle", "C2", "n."), ("delineate", "C2", "vt."), ("delusion", "C2", "n."),
    ("denounce", "C2", "vt."), ("depravity", "C2", "n."), ("dilapidated", "C2", "adj."),
    ("discern", "C2", "vt."), ("disparity", "C2", "n."), ("dissuade", "C2", "vt."),
    ("dogmatic", "C2", "adj."), ("dubious", "C2", "adj."), ("duplicity", "C2", "n."),
    ("eccentric", "C2", "adj."), ("egregious", "C2", "adj."), ("eloquent", "C2", "adj."),
    ("emancipate", "C2", "vt."), ("embezzle", "C2", "vt."), ("emulate", "C2", "vt."),
    ("ephemeral", "C2", "adj."), ("equivocal", "C2", "adj."), ("erudite", "C2", "adj."),
    ("esoteric", "C2", "adj."), ("euphemism", "C2", "n."), ("exacerbate", "C2", "vt."),
    ("exonerate", "C2", "vt."), ("expedient", "C2", "adj."), ("fallacious", "C2", "adj."),
    ("fastidious", "C2", "adj."), ("flippant", "C2", "adj."), ("fortuitous", "C2", "adj."),
    ("frugal", "C2", "adj."), ("futile", "C2", "adj."), ("grandiose", "C2", "adj."),
    ("hapless", "C2", "adj."), ("hegemony", "C2", "n."), ("heretical", "C2", "adj."),
    ("hypocritical", "C2", "adj."), ("ignominious", "C2", "adj."), ("impeccable", "C2", "adj."),
    ("imperative", "C2", "adj."), ("impunity", "C2", "n."), ("inadvertent", "C2", "adj."),
    ("incorrigible", "C2", "adj."), ("indignation", "C2", "n."), ("indomitable", "C2", "adj."),
    ("ineffable", "C2", "adj."), ("insidious", "C2", "adj."), ("intransigent", "C2", "adj."),
    ("irrelevant", "C2", "adj."), ("languish", "C2", "vi."), ("magnanimous", "C2", "adj."),
    ("malicious", "C2", "adj."), ("mendacious", "C2", "adj."), ("meticulous", "C2", "adj."),
    ("misnomer", "C2", "n."), ("mollify", "C2", "vt."), ("narcissistic", "C2", "adj."),
    ("nefarious", "C2", "adj."), ("nihilistic", "C2", "adj."), ("obliterate", "C2", "vt."),
    ("obstinate", "C2", "adj."), ("obtuse", "C2", "adj."), ("omnipotent", "C2", "adj."),
    ("opaque", "C2", "adj."), ("ostensible", "C2", "adj."), ("pernicious", "C2", "adj."),
    ("pertinent", "C2", "adj."), ("pervasive", "C2", "adj."), ("plethora", "C2", "n."),
    ("polemical", "C2", "adj."), ("pontificate", "C2", "vi."), ("portentous", "C2", "adj."),
    ("precarious", "C2", "adj."), ("precipitate", "C2", "vt."), ("predilection", "C2", "n."),
    ("preposterous", "C2", "adj."), ("prescient", "C2", "adj."), ("pretentious", "C2", "adj."),
    ("pristine", "C2", "adj."), ("profligate", "C2", "adj."), ("prosaic", "C2", "adj."),
    ("pugnacious", "C2", "adj."), ("querulous", "C2", "adj."), ("ramification", "C2", "n."),
    ("recalcitrant", "C2", "adj."), ("reclusive", "C2", "adj."), ("rectify", "C2", "vt."),
    ("relentless", "C2", "adj."), ("remorse", "C2", "n."), ("repudiate", "C2", "vt."),
    ("rescind", "C2", "vt."), ("reticent", "C2", "adj."), ("sanctimonious", "C2", "adj."),
    ("sanguine", "C2", "adj."), ("sardonic", "C2", "adj."), ("scrupulous", "C2", "adj."),
    ("sever", "C2", "vt."), ("sinister", "C2", "adj."), ("sophistry", "C2", "n."),
    ("spurious", "C2", "adj."), ("stoic", "C2", "adj."), ("subversive", "C2", "adj."),
    ("sycophant", "C2", "n."), ("taciturn", "C2", "adj."), ("tenacious", "C2", "adj."),
    ("terse", "C2", "adj."), ("treacherous", "C2", "adj."), ("trepidation", "C2", "n."),
    ("trivial", "C2", "adj."), ("truncate", "C2", "vt."), ("tumultuous", "C2", "adj."),
    ("ubiquitous", "C2", "adj."), ("unconscionable", "C2", "adj."), ("undermine", "C2", "vt."),
    ("unequivocal", "C2", "adj."), ("vacuous", "C2", "adj."), ("venerate", "C2", "vt."),
    ("vex", "C2", "vt."), ("vigilant", "C2", "adj."), ("vindicate", "C2", "vt."),
    ("virulent", "C2", "adj."), ("whimsical", "C2", "adj."), ("wield", "C2", "vt."),
    ("wistful", "C2", "adj."), ("zealous", "C2", "adj."),

    # ── 常見片語（B1 以上）────────────────────────────────────────────────
    ("carry out", "B1", "phrase"), ("come up with", "B1", "phrase"),
    ("deal with", "B1", "phrase"), ("find out", "B1", "phrase"),
    ("get used to", "B1", "phrase"), ("give up", "B1", "phrase"),
    ("keep up with", "B1", "phrase"), ("look forward to", "B1", "phrase"),
    ("make up for", "B1", "phrase"), ("point out", "B1", "phrase"),
    ("put off", "B1", "phrase"), ("run out of", "B1", "phrase"),
    ("set up", "B1", "phrase"), ("take part in", "B1", "phrase"),
    ("turn out", "B1", "phrase"), ("work out", "B1", "phrase"),
    ("break down", "B1", "phrase"), ("bring about", "B2", "phrase"),
    ("call for", "B2", "phrase"), ("come across", "B2", "phrase"),
    ("draw on", "B2", "phrase"), ("fall back on", "B2", "phrase"),
    ("get rid of", "B2", "phrase"), ("go along with", "B2", "phrase"),
    ("hold back", "B2", "phrase"), ("live up to", "B2", "phrase"),
    ("make sense of", "B2", "phrase"), ("narrow down", "B2", "phrase"),
    ("rule out", "B2", "phrase"), ("stand for", "B2", "phrase"),
    ("take into account", "B2", "phrase"), ("weigh up", "B2", "phrase"),
    ("boil down to", "C1", "phrase"), ("bring to light", "C1", "phrase"),
    ("cast doubt on", "C1", "phrase"), ("come to terms with", "C1", "phrase"),
    ("fall short of", "C1", "phrase"), ("give rise to", "C1", "phrase"),
    ("hold sway", "C1", "phrase"), ("lay the groundwork", "C1", "phrase"),
    ("pave the way for", "C1", "phrase"), ("put forward", "C1", "phrase"),
    ("shed light on", "C1", "phrase"), ("take a toll on", "C1", "phrase"),
    ("turn a blind eye", "C1", "phrase"), ("uphold the law", "C1", "phrase"),
]


def main():
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w", newline="", encoding="utf-8-sig") as F:
        Writer = csv.writer(F)
        Writer.writerow(["word", "cefr_level", "part_of_speech"])
        for Word, Level, Pos in WORDLIST:
            Writer.writerow([Word.lower(), Level, Pos])
    print(f"已寫入 {len(WORDLIST)} 筆詞彙到 {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
